name: Pharma ML Pipeline

on:
  push:
    branches: ['main']
  schedule:
    - cron: "30 14 * * *"  # Runs at morning 5 am everyday
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  Runnning-retraining-stages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        

      - name: Get Data from Remote Database
        run: python3 getData.py
        env:
          DB_USER: ${{secrets.DB_USER}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_NAME : ${{secrets.DB_NAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_PORT: ${{secrets.DB_PORT}}


      - name: Preprocess Data
        run: |
          python3 preprocessData.py  # Preprocess the data

      - name: Train the Model
        run: |
          python3 train.py  # Train the model


      - name: Predict Demand
        run: |
          python3 demand_predictor.py  # Predict demand

      - name: Calculate Supplier Score
        run: |
          python3 supplier_scorer.py  # Calculate supplier score

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add models/ state/ Data/
          git commit -m "Update by GitHub Actions bot on $(date)" || echo "No changes to commit"
          git push origin ${{ github.ref }}